kind: pipeline
type: kubernetes

# resource requests are defined on the pipeline level
resources:
  request:
    cpu: 2000
    memory: 2000MiB
  limit:
    cpu: 4000
    memory: 4000MiB
   
steps:
  - name: en
    image: alpine
    commands:
      - echo hello
    resources:
      # resource limits are defined for each step
      request:
        cpu: 50
        memory: 50MiB
      limit:
        cpu: 100
        memory: 100MiB

  - name: es
    image: alpine
    resources:
      # resource limits are defined for each step
      request:
        cpu: 3000
        memory: 300MiB
      limit:
        cpu: 5000
        memory: 500MiB
    commands:
      - echo hola

  - name: fr
    image: alpine
    commands:
      - echo bonjour
