---
kind: pipeline
name: default
type: kubernetes

resources:
  request:
    cpu: 1000
    memory: 200MiB

platform:
  os: linux
  arch: amd64

steps:
- name: run_tests
  image: python:3.9.2
  commands:
  - sleep 1020
  - python -c "print('sleep over')"

- name: step_2
  image: python:3.9.2
  commands:
  - python -c "print('step 2 begins')
