---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: stage-1
  image: alpine
  commands:
  - sleep 60

- name: stage-2
  image: alpine
  commands:
  - sleep 60
  resources:
    limits:
      cpu: 2
      memory: 15MiB
    requests:
      cpu: 1
      memory: 15MiB

- name: stage-3
  image: alpine
  commands:
  - sleep 60
  resources:
    limits:
      cpu: 205
      memory: 125MiB
    requests:
      cpu: 13
      memory: 42MiB

- name: stage-4
  image: alpine
  commands:
  - sleep 60
  resources:
    limits:
      cpu: 300
      memory: 300MiB
    requests:
      cpu: 265
      memory: 265MiB
